In [1]:
"""
GUV intensity analysis

Liv Jensen, Hurley Lab
University of California, Berkeley

Date Created: 2020-06-30
Date Updated: 2020-07-11

Analyzes multicolor fluorescence images to quantify fluorescence intensity at the 
perimeter of giant unilamellar vesicles (GUVs).

------------------
Some of this code is adapted from code written by Sy Redding and the Redding Lab
(github.com/ReddingLab/smtools), which is covered by the following license:
"MIT License

Copyright (c) 2018 Redding Lab, University of California, San Francisco

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."
----------------

The remainder of the code is under the following license:

Copyright (c) 2020 Hurley Lab, University of California, Berkeley

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. 
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from skimage import io
from skimage.filters import threshold_otsu, median, try_all_threshold
from skimage.morphology import disk
import scipy.ndimage.filters as filters
import os
%matplotlib tk

In [3]:
filelist = []
imfolder = os.getcwd()
label = "label"

if not imfolder.endswith(os.path.sep):
    imfolder += os.path.sep

for i in os.listdir(imfolder):
    if i.endswith(".tif"):
        filelist.append(i)

selem = disk(3)
for x in filelist:
    fname = imfolder + x
    im = io.imread(fname)
    c1 = im[:, :, :, 0]
    lipid= im[:, :, :, 2]
    signal = np.zeros((len(lipid)))
    size = (5, 5)
    
# defines local maxima in the lipid channel
    for i in range(len(lipid)):
        im_max = filters.maximum_filter(lipid[i], size)
        im_min = filters.minimum_filter(lipid[i], size)
        im_diff = im_max - im_min
        thresh = threshold_otsu(im_diff)
        ##thresh = thresh / 2
        bool_diff = (im_diff <= thresh)

        ##fig, ax = try_all_threshold(im_diff, figsize=(10, 8), verbose=False)
        ##plt.show()

    ####################
# takes average of channel 1 pixel values that are colocalized with local maxima in the lipid channel    
        masked_c1 = c1[i].copy()
        masked_c1[bool_diff] = 0
        c1av = np.average(masked_c1[masked_c1 != 0])
        
    ####################
# defines background intensity as the average of 2 background values: inside-vesicle and outside-vesicle backgrounds.
# outside-background calculated for each frame is the average of non-foreground pixel values
        backgroundout = np.average(c1[i][masked_c1 == 0]) 
    
# inside-background calculated from user input of location of a vesicle in the first frame of a timecourse,
# from which the local median pixel value is used as inside background.
        if i == 0:
            plt.imshow(masked_c1)
            insidepix = plt.ginput(1, show_clicks=True)
            c1blur = median(c1[i], selem=selem)

            backgroundin = c1blur[int(round(insidepix[0][1])), int(round(insidepix[0][0]))]
        background = (backgroundout + backgroundin)/2
        
# calculates background-subtracted signal
        signal[i] = c1av - background
    
    signal_df = pd.DataFrame(data=signal, columns=[x])
    if filelist.index(x) == 0:
        result = signal_df
    else:
        result = pd.concat([result, signal_df], axis=1)

# saves data as a .csv file        
##np.savetxt(imfolder+label+"data.csv", signal, delimiter=',')
result.to_csv(path_or_buf=imfolder+label+"data.csv", sep=",", index=False)

[[221 217 213 ... 208 183 183]
 [217 215 206 ... 208 197 191]
 [209 209 205 ... 214 208 215]
 ...
 [192 201 206 ... 250 250 251]
 [192 196 201 ... 250 250 227]
 [192 196 201 ... 240 227 204]]
